// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cli$0 from "../cli/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as poll$0 from "../poll/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Agents(): $CancellablePromise<poll$0.Agent[] | null> {
    return $Call.ByID(693732554);
}

export function CheckpointCreate(name: string, label: string): $CancellablePromise<void> {
    return $Call.ByID(1559967510, name, label);
}

export function CheckpointList(name: string): $CancellablePromise<string> {
    return $Call.ByID(4129538782, name);
}

export function CheckpointRestore(name: string, ref: string): $CancellablePromise<void> {
    return $Call.ByID(2192857000, name, ref);
}

/**
 * Clone spawns a fresh session with the same agent type, repos and SSH mode
 * as an existing container (config reconstructed from its env + labels).
 */
export function Clone(name: string): $CancellablePromise<string> {
    return $Call.ByID(2001323193, name);
}

/**
 * CloneLocalFolder streams a host directory into <container>:/workspace/<base>
 * as a gzip tar over `container machine run -i … docker exec -i` (same stdin
 * relay the setup build-context sync uses). Skips .git and heavy build dirs.
 */
export function CloneLocalFolder(container: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(1573691384, container, localPath);
}

/**
 * ConfigSync pushes current host Claude settings into the container;
 * restart applies them immediately (the session resumes).
 */
export function ConfigSync(name: string, restart: boolean): $CancellablePromise<string> {
    return $Call.ByID(95632153, name, restart);
}

export function Cost(name: string): $CancellablePromise<string> {
    return $Call.ByID(2020914969, name);
}

export function CostHistory(window: string): $CancellablePromise<string> {
    return $Call.ByID(2624464075, window);
}

export function Diff(name: string): $CancellablePromise<string> {
    return $Call.ByID(587789987, name);
}

/**
 * OpenURL opens an http(s) URL in the host's default browser.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(2120322749, url);
}

export function Output(name: string): $CancellablePromise<cli$0.OutputInfo> {
    return $Call.ByID(1181229993, name);
}

export function PR(name: string): $CancellablePromise<void> {
    return $Call.ByID(1098575466, name);
}

/**
 * PR looks up the PR for the agent's checked-out branch via gh in its
 * workspace. Empty PRInfo (no error) when the agent has no repo/PR.
 */
export function PRStatus(name: string, repoDisplay: string): $CancellablePromise<$models.PRInfo> {
    return $Call.ByID(3159238996, name, repoDisplay);
}

/**
 * PickFolder opens the native directory picker (wired to Wails in main).
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(86929653);
}

/**
 * PipelineRun runs (or --dry-run validates) a saved pipeline by name, passing
 * any ${vars} the manifest declares as --var key=value.
 */
export function PipelineRun(name: string, vars: { [_ in string]?: string } | null, dryRun: boolean): $CancellablePromise<string> {
    return $Call.ByID(2852768419, name, vars, dryRun);
}

export function Refresh(): $CancellablePromise<void> {
    return $Call.ByID(3662288047);
}

export function Retry(name: string, feedback: string): $CancellablePromise<void> {
    return $Call.ByID(4119827342, name, feedback);
}

export function Review(name: string): $CancellablePromise<void> {
    return $Call.ByID(4193130360, name);
}

export function Spawn(req: $models.SpawnRequest): $CancellablePromise<string> {
    return $Call.ByID(3528838075, req);
}

/**
 * SpawnFromLocal spawns a blank-workspace agent and streams a local folder
 * into it, so the agent works on a copy of a laptop directory (no git URL).
 */
export function SpawnFromLocal(agent: string, localPath: string): $CancellablePromise<string> {
    return $Call.ByID(1432195030, agent, localPath);
}

export function Steer(name: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(391136501, name, message);
}

export function Stop(name: string): $CancellablePromise<void> {
    return $Call.ByID(1027892044, name);
}

export function TemplateList(): $CancellablePromise<string> {
    return $Call.ByID(3182057434);
}

/**
 * VMRepair re-runs the idempotent `safe-ag setup` — re-hardens the machine,
 * reconciles Docker/NAT, and rebuilds support files. The heavy "reset" option.
 */
export function VMRepair(): $CancellablePromise<string> {
    return $Call.ByID(3438583656);
}

/**
 * VMRestart stops then starts the machine (the CLI has no single restart).
 */
export function VMRestart(): $CancellablePromise<string> {
    return $Call.ByID(384939432);
}

export function VMStart(): $CancellablePromise<string> {
    return $Call.ByID(3472829651);
}

export function VMStop(): $CancellablePromise<string> {
    return $Call.ByID(637685665);
}

export function WorkspaceRevert(name: string): $CancellablePromise<void> {
    return $Call.ByID(1836280415, name);
}

export function WorkspaceRevertPath(name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2651970552, name, path);
}

/**
 * Stage/Revert operate on the whole workspace: the CLI requires explicit
 * paths ("." = everything).
 */
export function WorkspaceStage(name: string): $CancellablePromise<void> {
    return $Call.ByID(2028950633, name);
}

export function WorkspaceStagePath(name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1976009906, name, path);
}
