// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cli$0 from "../cli/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as poll$0 from "../poll/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Agents(): $CancellablePromise<poll$0.Agent[] | null> {
    return $Call.ByID(693732554);
}

export function CheckpointCreate(name: string, label: string): $CancellablePromise<void> {
    return $Call.ByID(1559967510, name, label);
}

export function CheckpointList(name: string): $CancellablePromise<string> {
    return $Call.ByID(4129538782, name);
}

export function CheckpointRestore(name: string, ref: string): $CancellablePromise<void> {
    return $Call.ByID(2192857000, name, ref);
}

export function Cost(name: string): $CancellablePromise<string> {
    return $Call.ByID(2020914969, name);
}

export function CostHistory(window: string): $CancellablePromise<string> {
    return $Call.ByID(2624464075, window);
}

export function Diff(name: string): $CancellablePromise<string> {
    return $Call.ByID(587789987, name);
}

export function Output(name: string): $CancellablePromise<cli$0.OutputInfo> {
    return $Call.ByID(1181229993, name);
}

export function PR(name: string): $CancellablePromise<void> {
    return $Call.ByID(1098575466, name);
}

export function PipelineRun(file: string): $CancellablePromise<string> {
    return $Call.ByID(2852768419, file);
}

export function Refresh(): $CancellablePromise<void> {
    return $Call.ByID(3662288047);
}

export function Retry(name: string, feedback: string): $CancellablePromise<void> {
    return $Call.ByID(4119827342, name, feedback);
}

export function Review(name: string): $CancellablePromise<void> {
    return $Call.ByID(4193130360, name);
}

export function Spawn(req: $models.SpawnRequest): $CancellablePromise<string> {
    return $Call.ByID(3528838075, req);
}

export function Steer(name: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(391136501, name, message);
}

export function Stop(name: string): $CancellablePromise<void> {
    return $Call.ByID(1027892044, name);
}

export function TemplateList(): $CancellablePromise<string> {
    return $Call.ByID(3182057434);
}

export function VMStart(): $CancellablePromise<string> {
    return $Call.ByID(3472829651);
}

export function WorkspaceRevert(name: string): $CancellablePromise<void> {
    return $Call.ByID(1836280415, name);
}

/**
 * Stage/Revert operate on the whole workspace: the CLI requires explicit
 * paths ("." = everything).
 */
export function WorkspaceStage(name: string): $CancellablePromise<void> {
    return $Call.ByID(2028950633, name);
}
