// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface SpawnRequest {
    "Agent": string;
    "Repo": string;
    "Prompt": string;
    "Template": string;
    "Network": string;
    "Memory": string;
    "CPUs": string;
    "SSH": boolean;
    "ReuseAuth": boolean;
    "Worktree": boolean;
    "DryRun": boolean;
}
