// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Close(id: string): $CancellablePromise<void> {
    return $Call.ByID(952659619, id);
}

export function Open(container: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(1079702345, container, cols, rows);
}

export function Redraw(id: string): $CancellablePromise<void> {
    return $Call.ByID(3063660242, id);
}

export function Resize(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(269798433, id, cols, rows);
}

export function Write(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3475231452, id, data);
}
