// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface OutputInfo {
    "name": string;
    "status": string;
    "last_output": string;
    "files": string[] | null;
    "commits": string[] | null;
}
