// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audit$0 from "../../../pkg/audit/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AuditTail(n: number): $CancellablePromise<audit$0.Entry[] | null> {
    return $Call.ByID(2254927521, n);
}

export function EventsTail(n: number): $CancellablePromise<$models.EventItem[] | null> {
    return $Call.ByID(602569971, n);
}

export function Inbox(n: number): $CancellablePromise<$models.EventItem[] | null> {
    return $Call.ByID(3385797668, n);
}

export function PipelineFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2603917901);
}

export function ProjectRemove(url: string): $CancellablePromise<void> {
    return $Call.ByID(3307348241, url);
}

/**
 * ProjectUse bumps the use count, adding the repo if new.
 */
export function ProjectUse(url: string): $CancellablePromise<void> {
    return $Call.ByID(2231767688, url);
}

/**
 * Projects returns saved repos sorted by use count desc, then recency desc.
 */
export function Projects(): $CancellablePromise<$models.Project[] | null> {
    return $Call.ByID(118778646);
}
