// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cli$0 from "../cli/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as poll$0 from "../poll/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audit$0 from "../../../pkg/audit/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Agents(): $CancellablePromise<poll$0.Agent[] | null> {
    return $Call.ByID(493595822);
}

/**
 * AuditFor returns this container's audit entries, filtered server-side BEFORE
 * truncating to limit (so a busy neighbour can't push a quiet agent's rows out
 * of a global tail). limit<=0 returns all matching entries.
 */
export function AuditFor(name: string, limit: number): $CancellablePromise<audit$0.Entry[] | null> {
    return $Call.ByID(454168434, name, limit);
}

export function CheckpointCreate(name: string, label: string): $CancellablePromise<void> {
    return $Call.ByID(1203724930, name, label);
}

export function CheckpointList(name: string): $CancellablePromise<string> {
    return $Call.ByID(1982986674, name);
}

export function CheckpointRestore(name: string, ref: string): $CancellablePromise<void> {
    return $Call.ByID(1609975156, name, ref);
}

/**
 * Clone spawns a fresh session with the same agent type, repos and SSH mode
 * as an existing container (config reconstructed from its env + labels).
 */
export function Clone(name: string): $CancellablePromise<string> {
    return $Call.ByID(1158028581, name);
}

/**
 * CloneLocalFolder streams a host directory into <container>:/workspace/<base>
 * as a gzip tar over `container machine run -i … docker exec -i` (same stdin
 * relay the setup build-context sync uses). Skips .git and heavy build dirs.
 */
export function CloneLocalFolder(container: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(4134394540, container, localPath);
}

/**
 * CommandLog returns the recent executed berth commands (the console feed).
 */
export function CommandLog(): $CancellablePromise<cli$0.CommandEntry[] | null> {
    return $Call.ByID(1710861373);
}

/**
 * ConfigSync pushes current host Claude settings into the container;
 * restart applies them immediately (the session resumes).
 */
export function ConfigSync(name: string, restart: boolean): $CancellablePromise<string> {
    return $Call.ByID(916041125, name, restart);
}

export function Cost(name: string): $CancellablePromise<string> {
    return $Call.ByID(1052200653, name);
}

export function CostHistory(window: string): $CancellablePromise<string> {
    return $Call.ByID(2760188247, window);
}

/**
 * CostSummary returns `berth cost <name>` stdout, pairing with the MaxCost
 * budget surfaced on the agent card.
 */
export function CostSummary(name: string): $CancellablePromise<string> {
    return $Call.ByID(733215835, name);
}

/**
 * Diagnose returns `berth diagnose` stdout. Uses the long timeout — diagnose
 * probes the VM/Docker/NAT and can take well over the default budget.
 */
export function Diagnose(): $CancellablePromise<string> {
    return $Call.ByID(3746217104);
}

export function Diff(name: string): $CancellablePromise<string> {
    return $Call.ByID(3507026271, name);
}

/**
 * OpenURL opens an http(s) URL in the host's default browser.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(2543197025, url);
}

export function Output(name: string): $CancellablePromise<cli$0.OutputInfo> {
    return $Call.ByID(1862776229, name);
}

export function PR(name: string): $CancellablePromise<string> {
    return $Call.ByID(2178911310, name);
}

/**
 * PR looks up the PR for the agent's checked-out branch via gh in its
 * workspace. Empty PRInfo (no error) when the agent has no repo/PR.
 */
export function PRStatus(name: string, repoDisplay: string): $CancellablePromise<$models.PRInfo> {
    return $Call.ByID(2038864880, name, repoDisplay);
}

/**
 * PickFolder opens the native directory picker (wired to Wails in main).
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(4279425665);
}

/**
 * PipelineRun runs (or --dry-run validates) a saved pipeline by name, passing
 * any ${vars} the manifest declares as --var key=value.
 */
export function PipelineRun(name: string, vars: { [_ in string]?: string } | null, dryRun: boolean): $CancellablePromise<string> {
    return $Call.ByID(2281522943, name, vars, dryRun);
}

export function Refresh(): $CancellablePromise<void> {
    return $Call.ByID(295810323);
}

export function Retry(name: string, feedback: string): $CancellablePromise<void> {
    return $Call.ByID(1144104426, name, feedback);
}

export function Review(name: string): $CancellablePromise<string> {
    return $Call.ByID(1924006668, name);
}

export function Spawn(req: $models.SpawnRequest): $CancellablePromise<string> {
    return $Call.ByID(4115293367, req);
}

/**
 * SpawnFromLocal spawns a blank-workspace agent and streams a local folder
 * into it, so the agent works on a copy of a laptop directory (no git URL).
 */
export function SpawnFromLocal(agent: string, localPath: string): $CancellablePromise<string> {
    return $Call.ByID(1409442586, agent, localPath);
}

export function Steer(name: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3156311465, name, message);
}

export function Stop(name: string): $CancellablePromise<void> {
    return $Call.ByID(881467568, name);
}

export function TemplateList(): $CancellablePromise<string> {
    return $Call.ByID(3423406350);
}

/**
 * VMRepair re-runs the idempotent `berth setup` — re-hardens the machine,
 * reconciles Docker/NAT, and rebuilds support files. The heavy "reset" option.
 */
export function VMRepair(): $CancellablePromise<string> {
    return $Call.ByID(2889144868);
}

/**
 * VMRestart stops then starts the machine (the CLI has no single restart).
 */
export function VMRestart(): $CancellablePromise<string> {
    return $Call.ByID(3603049916);
}

export function VMStart(): $CancellablePromise<string> {
    return $Call.ByID(437553615);
}

export function VMStop(): $CancellablePromise<string> {
    return $Call.ByID(239495061);
}

export function WorkspaceRevert(name: string): $CancellablePromise<void> {
    return $Call.ByID(4236803763, name);
}

export function WorkspaceRevertPath(name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2685527284, name, path);
}

/**
 * Stage/Revert operate on the whole workspace: the CLI requires explicit
 * paths ("." = everything).
 */
export function WorkspaceStage(name: string): $CancellablePromise<void> {
    return $Call.ByID(1023402237, name);
}

export function WorkspaceStagePath(name: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3093738398, name, path);
}
