// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PRInfo is the open pull request for the agent's current branch, if any.
 */
export interface PRInfo {
    "url": string;
    "number": number;
    "state": string;
    "title": string;
}

/**
 * Quota is one agent's quota, or an Error explaining why it's unavailable.
 */
export interface Quota {
    /**
     * "claude" | "codex"
     */
    "agent": string;
    "ok": boolean;
    "error": string;
    "windows": QuotaWindow[] | null;
}

/**
 * QuotaWindow is one rate-limit window (used percent + reset time).
 */
export interface QuotaWindow {
    /**
     * "5h" | "week"
     */
    "label": string;

    /**
     * used, 0..100
     */
    "percent": number;

    /**
     * unix seconds; 0 if unknown
     */
    "resetsAt": number;
}

export interface SpawnRequest {
    "Agent": string;
    "Name": string;
    "Repo": string;
    "Prompt": string;
    "Template": string;
    "Network": string;
    "Memory": string;
    "CPUs": string;

    /**
     * USD budget label (advisory)
     */
    "MaxCost": string;

    /**
     * local checkout for --worktree (the CLI worktrees its cwd)
     */
    "WorktreeDir": string;

    /**
     * standing instructions added to the agent's context
     */
    "Instructions": string;

    /**
     * ~/.aws profile injected as env creds
     */
    "AWSProfile": string;
    "SSH": boolean;
    "ReuseAuth": boolean;
    "Worktree": boolean;
    "DryRun": boolean;
    "NoSeedAuth": boolean;
    "NoGHAuth": boolean;
}
