// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QuotaService reports remaining subscription quota for the host's Claude and
 * Codex logins. Both agents expose a 5-hour window and a weekly window as
 * used-percent; the app renders them as bars.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Quotas returns Claude then Codex quota. Never errors: a per-agent failure is
 * carried in that Quota's Error so the other still renders.
 */
export function Quotas(): $CancellablePromise<$models.Quota[] | null> {
    return $Call.ByID(920675276);
}
