// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Close(id: string): $CancellablePromise<void> {
    return $Call.ByID(2557146887, id);
}

export function Open(container: string, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByID(2433084277, container, cols, rows);
}

export function Redraw(id: string): $CancellablePromise<void> {
    return $Call.ByID(4153998702, id);
}

export function Resize(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(631835077, id, cols, rows);
}

export function Write(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(971866864, id, data);
}
