// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Agent {
    "Name": string;
    "Type": string;
    "Repo": string;
    "SSH": string;
    "Auth": string;
    "GHAuth": string;
    "Docker": string;
    "NetworkMode": string;
    "Fleet": string;
    "Hierarchy": string;
    "Terminal": string;
    "Status": string;
    "Running": boolean;
    "Finished": boolean;

    /**
     * "Working" | "Idle" | "Stopped"
     */
    "Activity": string;

    /**
     * agentstate: blocked/working/done/idle/exited/unknown (set by poller probe)
     */
    "State": string;
    "StateReason": string;
    "CPU": string;
    "Memory": string;
    "NetIO": string;
    "PIDs": string;

    /**
     * from docker labels (immutable per container, cached)
     */
    "Prompt": string;
    "MaxCost": string;
}
