// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandEntry is one executed berth invocation, for the command console.
 */
export interface CommandEntry {
    /**
     * unix milliseconds
     */
    "ts": number;

    /**
     * secret/token values redacted
     */
    "argv": string[] | null;

    /**
     * exit status
     */
    "ok": boolean;

    /**
     * wall time
     */
    "durationMs": number;

    /**
     * last non-empty output line
     */
    "tail": string;
}

export interface OutputInfo {
    "name": string;
    "status": string;
    "last_output": string;
    "files": string[] | null;
    "commits": string[] | null;
}
