// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface EventItem {
    "timestamp": string;
    "type": string;
    "payload": { [_ in string]?: string } | null;
    "status": string;
    "container": string;
}

export interface Project {
    "url": string;
    "count": number;
    "last": number;
}
